services:
  - type: web
    name: fastapi-gemini-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PIP_VERSION
        value: "23.3.1"